version: '3'
services:
  db:
    image: postgres:13.5
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  webpack:
    build: .
    command: ./bin/webpack --watch --progress
    volumes:
      - .:/app
    ports:
      - '3035:3035'
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db